Author.create!([
  {name: "Elísio da Fronteira", bio: "Who the hell is John F. Kennedy?"},
  {name: "Dra. Daniel Grotas", bio: "The appropriate question is, 'when the hell are they?' You see, Einstein has just become the world's first time traveler! I sent him into the future. One minute into the future to be exact. And at precisely 1:21 a.m. and zero seconds, we shall catch up with him and the time machine."},
  {name: "Kaique Dantas", bio: "Wait a minute. Wait a minute, Doc. Ah... Are you telling me that you built a time machine... out of a DeLorean?"},
  {name: "Giovanna Brites", bio: "You want a Pepsi, pal, you're gonna pay for it."},
  {name: "Dr. Liz Batista", bio: "Calm down, Marty. I didn't disintegrate anything. The molecular structure of both Einstein and the car are completely intact."},
  {name: "Olívia Custódio", bio: "You're late! Do you have no concept of time?"},
  {name: "Arthur Miguel Casqueira", bio: "Okay, thank you. That's enough. Hold it now. Hold it. Hold it, fellas. I'm afraid you're just too darn loud. Next, please. Bring in the next group, please."},
  {name: "Yuri Galego", bio: "Hey, come on. I had to change. Do you think I'm going back in that-that zoot suit? The old man really came through. It worked!"},
  {name: "Dr. Pedro da Madureira", bio: "Course! From a group of Lybian Nationalists They wanted me to build them a bomb, so I took their plutonium and in turn I gave them a shiny bomb caseing full of used pinball machine parts!"},
  {name: "Morgana Fogaça Filho", bio: "Things have certainly changed around here. I remember when this was all farmland as far the eye could see. Old man Peabody owned all of this. He had this crazy idea about breeding pine trees."},
  {name: "Theo Siqueira", bio: "I g-guess you guys aren't ready for that yet. But your kids are gonna love it."},
  {name: "Sra. Mariana Nascimento", bio: "And one for you, McFly; I believe that makes four in a row. Now let me give you a nickel's worth of free advice, young man. This so-called Dr. Brown is dangerous. He's a real nutcase. You hang around with him, you're gonna end up in big trouble."},
  {name: "Maria Vitória Aguiar", bio: "This is all wrong. I don't know what it is. But when I kiss you, it's like I'm kissing... my brother. I guess that doesn't make any sense, does it?"},
  {name: "Sirineu Freitas", bio: "What happens to us in the future? Do we become assholes or something?"},
  {name: "Carlos Pires", bio: "There's that word again. 'Heavy.' Why are things so heavy in the future? Is there a problem with the Earth's gravitational pull?"},
  {name: "Luna da Fonseca", bio: "Hey, McFly! I thought I told you never to come in here."},
  {name: "Pedro Ornelas", bio: "Stand tall, boy. Have some respect for yourself. Don't you know, if you let people walk over you now, they'll be walking over you for the rest of your life. Look at me. You think I'm gonna spend the rest of my life in this slop house?"},
  {name: "Luiz Henrique Viveiros", bio: "Weight has nothing to do with it."},
  {name: "João Felipe da Nóbrega Jr.", bio: "What happens to us in the future? Do we become assholes or something?"},
  {name: "João Luca Freitas", bio: "Silence, Earthling. My name is Darth Vader. I am an extraterrestrial from the planet Vulcan!"},
  {name: "Ana Cecília Bittencourt", bio: "Who the hell is John F. Kennedy?"},
  {name: "Benício Barroso Neto", bio: "Hello? Hello? Anybody home? Huh? Think, McFly. Think! I gotta have time to get them retyped. Do you realize what would happen if I hand in my reports in your handwriting? I'll get fired. You wouldn't want that to happen, would ya? Would ya?"},
  {name: "Srta. Bruna Goulart", bio: "Scram, McFly. I'm cuttin' in."},
  {name: "Maria Fernanda Veles", bio: "You're late! Do you have no concept of time?"},
  {name: "Emanuelly da Penha", bio: "The way I see it, if you're gonna build a time machine into a car, why not do it with some style?"},
  {name: "Sra. Isabelly Conceição", bio: "Great Scott!"},
  {name: "Morgana Ribeira Jr.", bio: "Ah, Jesus Christ! Jesus Christ, Doc, you disintegrated Einstein!"},
  {name: "Davi Camacho", bio: "So you're my Uncle Joey. Better get used to these bars, kid."},
  {name: "Lívia Ramires", bio: "Since you're new here, I-I'm gonna cut you a break, today. So, why don't you make like a tree and get outta here?"},
  {name: "Srta. Gúbio Antunes", bio: "He's an idiot. Comes from upbringing. His parents are probably idiots, too. Lorraine, you ever have a kid who acts that way, I'll disown you."}
])

Genre.create!([
  {name: "Apocalipse Zumbi"},
  {name: "Autobiografia"},
  {name: "Biografia"},
  {name: "Chick-Lit"},
  {name: "Fantasia e Fantasia Científica"},
  {name: "Ficção Científica: na Literatura e também nas Revistas e Gibis"},
  {name: "Folhetim"},
  {name: "Horror"},
  {name: "Literatura Brutalista"},
  {name: "Literatura Fantástica"},
  {name: "Literatura Infanto-Juvenil"},
  {name: "Literatura YA – Young Adult – Jovem Adulto"},
  {name: "Metaficção"},
  {name: "Neocrítica"},
  {name: "Novelas de Cavalaria"},
  {name: "Paródia"},
  {name: "Sick-Lit"},
  {name: "Space Opera"},
  {name: "Suspense"},
  {name: "Vampirismo"},
  {name: "Literatura Gótica"},
  {name: "Literatura Esotérica"},
  {name: "Romances Espíritas"},
  {name: "Literatura de Auto-Ajuda"},
  {name: "Literatura de Negócios"},
  {name: "Literatura Steampunk"},
  {name: "Literatura Cyberpunk"},
  {name: "Literatura Espiritualista"},
  {name: "Literatura de Aventura"},
  {name: "Literatura de Guerra"}
])

Book.create!([
  {name: "Nine Coaches Waiting", genre_id: 16, author_id: 1},
  {name: "To Sail Beyond the Sunset", genre_id: 14, author_id: 17},
  {name: "The Last Enemy", genre_id: 6, author_id: 9},
  {name: "Moab Is My Washpot", genre_id: 23, author_id: 10},
  {name: "Noli Me Tangere", genre_id: 8, author_id: 25},
  {name: "Unweaving the Rainbow", genre_id: 20, author_id: 1},
  {name: "Carrion Comfort", genre_id: 21, author_id: 11},
  {name: "Jesting Pilate", genre_id: 27, author_id: 9},
  {name: "Let Us Now Praise Famous Men", genre_id: 23, author_id: 15},
  {name: "Tirra Lirra by the River", genre_id: 23, author_id: 25},
  {name: "Of Mice and Men", genre_id: 30, author_id: 24},
  {name: "The Violent Bear It Away", genre_id: 20, author_id: 25},
  {name: "An Instant In The Wind", genre_id: 22, author_id: 21},
  {name: "The Soldier's Art", genre_id: 17, author_id: 4},
  {name: "The Moving Toyshop", genre_id: 5, author_id: 30},
  {name: "A Catskill Eagle", genre_id: 30, author_id: 27},
  {name: "East of Eden", genre_id: 27, author_id: 26},
  {name: "Moab Is My Washpot", genre_id: 30, author_id: 9},
  {name: "The Sun Also Rises", genre_id: 13, author_id: 18},
  {name: "The Heart Is a Lonely Hunter", genre_id: 8, author_id: 8},
  {name: "This Lime Tree Bower", genre_id: 26, author_id: 14},
  {name: "After Many a Summer Dies the Swan", genre_id: 12, author_id: 16},
  {name: "For a Breath I Tarry", genre_id: 20, author_id: 12},
  {name: "The Wives of Bath", genre_id: 17, author_id: 7},
  {name: "An Instant In The Wind", genre_id: 2, author_id: 2},
  {name: "Blue Remembered Earth", genre_id: 25, author_id: 10},
  {name: "The Widening Gyre", genre_id: 20, author_id: 7},
  {name: "Now Sleeps the Crimson Petal", genre_id: 4, author_id: 19},
  {name: "For Whom the Bell Tolls", genre_id: 9, author_id: 4},
  {name: "The Heart Is a Lonely Hunter", genre_id: 7, author_id: 6},
  {name: "A Time of Gifts", genre_id: 22, author_id: 11},
  {name: "Far From the Madding Crowd", genre_id: 8, author_id: 28},
  {name: "A Confederacy of Dunces", genre_id: 9, author_id: 1},
  {name: "Jacob Have I Loved", genre_id: 28, author_id: 17},
  {name: "The Daffodil Sky", genre_id: 23, author_id: 23},
  {name: "The Cricket on the Hearth", genre_id: 22, author_id: 21},
  {name: "Brandy of the Damned", genre_id: 14, author_id: 16},
  {name: "An Acceptable Time", genre_id: 28, author_id: 24},
  {name: "The Curious Incident of the Dog in the Night-Time", genre_id: 27, author_id: 10},
  {name: "A Catskill Eagle", genre_id: 18, author_id: 6},
  {name: "The Other Side of Silence", genre_id: 22, author_id: 4},
  {name: "The Doors of Perception", genre_id: 19, author_id: 26},
  {name: "A Confederacy of Dunces", genre_id: 29, author_id: 4},
  {name: "The Mirror Crack'd from Side to Side", genre_id: 25, author_id: 13},
  {name: "Antic Hay", genre_id: 26, author_id: 12},
  {name: "The Cricket on the Hearth", genre_id: 7, author_id: 23},
  {name: "The Wind's Twelve Quarters", genre_id: 6, author_id: 4},
  {name: "O Pioneers!", genre_id: 26, author_id: 24},
  {name: "Clouds of Witness", genre_id: 10, author_id: 29},
  {name: "An Evil Cradling", genre_id: 24, author_id: 7},
  {name: "Cover Her Face", genre_id: 26, author_id: 12},
  {name: "Fair Stood the Wind for France", genre_id: 19, author_id: 21},
  {name: "A Time to Kill", genre_id: 13, author_id: 27},
  {name: "The Grapes of Wrath", genre_id: 11, author_id: 1},
  {name: "Cover Her Face", genre_id: 27, author_id: 14},
  {name: "By Grand Central Station I Sat Down and Wept", genre_id: 30, author_id: 23},
  {name: "No Country for Old Men", genre_id: 2, author_id: 18},
  {name: "To Your Scattered Bodies Go", genre_id: 10, author_id: 3},
  {name: "The Mirror Crack'd from Side to Side", genre_id: 25, author_id: 22},
  {name: "Far From the Madding Crowd", genre_id: 21, author_id: 14},
  {name: "A Scanner Darkly", genre_id: 9, author_id: 22},
  {name: "Cabbages and Kings", genre_id: 26, author_id: 15},
  {name: "This Lime Tree Bower", genre_id: 27, author_id: 7},
  {name: "All the King's Men", genre_id: 11, author_id: 5},
  {name: "The Golden Bowl", genre_id: 23, author_id: 3},
  {name: "Look to Windward", genre_id: 10, author_id: 25},
  {name: "An Acceptable Time", genre_id: 19, author_id: 13},
  {name: "Specimen Days", genre_id: 11, author_id: 21},
  {name: "A Glass of Blessings", genre_id: 2, author_id: 5},
  {name: "Bury My Heart at Wounded Knee", genre_id: 8, author_id: 17},
  {name: "This Lime Tree Bower", genre_id: 18, author_id: 11},
  {name: "The Wings of the Dove", genre_id: 22, author_id: 10},
  {name: "Dying of the Light", genre_id: 14, author_id: 11},
  {name: "The Curious Incident of the Dog in the Night-Time", genre_id: 18, author_id: 19},
  {name: "The Daffodil Sky", genre_id: 1, author_id: 29},
  {name: "Oh! To be in England", genre_id: 12, author_id: 12},
  {name: "A Scanner Darkly", genre_id: 30, author_id: 22},
  {name: "The Proper Study", genre_id: 17, author_id: 5},
  {name: "The Torment of Others", genre_id: 6, author_id: 26},
  {name: "All Passion Spent", genre_id: 18, author_id: 6},
  {name: "Brandy of the Damned", genre_id: 24, author_id: 15},
  {name: "Mother Night", genre_id: 26, author_id: 17},
  {name: "Moab Is My Washpot", genre_id: 26, author_id: 9},
  {name: "The Wealth of Nations", genre_id: 1, author_id: 28},
  {name: "No Highway", genre_id: 15, author_id: 5},
  {name: "Cover Her Face", genre_id: 22, author_id: 26},
  {name: "The Little Foxes", genre_id: 28, author_id: 5},
  {name: "The Golden Bowl", genre_id: 21, author_id: 14},
  {name: "All Passion Spent", genre_id: 19, author_id: 8},
  {name: "Terrible Swift Sword", genre_id: 19, author_id: 11},
  {name: "Arms and the Man", genre_id: 30, author_id: 29},
  {name: "All Passion Spent", genre_id: 6, author_id: 3},
  {name: "By Grand Central Station I Sat Down and Wept", genre_id: 1, author_id: 5},
  {name: "Beneath the Bleeding", genre_id: 9, author_id: 14},
  {name: "Fear and Trembling", genre_id: 28, author_id: 10},
  {name: "Unweaving the Rainbow", genre_id: 8, author_id: 23},
  {name: "In a Glass Darkly", genre_id: 17, author_id: 26},
  {name: "Cabbages and Kings", genre_id: 5, author_id: 3},
  {name: "A Monstrous Regiment of Women", genre_id: 14, author_id: 30},
  {name: "The Moon by Night", genre_id: 21, author_id: 26}
])
